### PR TITLE
Simcenter Amesim and Webapp Server 2210

### PR DESCRIPTION
**Pull request by BrunoLione**
Hi Filip, thanks for your previous commits to the main branch. I could also visualize/preview the result in the Github.dev tool and fix the display of pictures.

### CODE REVIEW

**Comment by BrunoLione** [comment]
Reopening as closing could be seen as incorrect.

**Comment by BrunoLione** [comment]
Pushed new article from a colleague for Webapp. Still need to update the picture to comply with the guidelines

**Comment by BrunoLione** [comment]
This pull request eventually contains two articles: one for Simcenter Amesim and one for Simcenter Webapp Server

**Comment by filip-jezek** [comment]
Bruno, I had to trim your contribution down, you have to leave some space to others too ;) Also it was too much of an advertisement already. However, given there was no prior notice and you have submitted that early enough to have this feedback sooner, I have included all your text into separate files hosted with the newsletter.

The newsletter is sent with the headings only in the email, so if you need to rephrase some text you can still do that whenever you like.

**Comment by BrunoLione** [comment]
Hi Filip,

OK, I only made some small changes for punctuation. Next time, I will try
to make a much shorter article. I tried the links to the auxiliary files
but they do not seem to work (at least on Github).
I let you check this.
Regards,
-- 
Bruno


Le sam. 19 nov. 2022 à 21:36, Filip Ježek ***@***.***> a
écrit :

**Pull request merged**
